name: Luacheck
on: [pull_request]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Luacheck Linter
        run: |
          echo "##[group]Install luacheck"
          if ! hash luacheck &>/dev/null; then
            sudo apt-get install -yq luarocks 1>/dev/null || exit 1
            sudo luarocks install luacheck 1>/dev/null || exit 1
            sudo luarocks install lanes &>/dev/null || true
          fi
          echo "##[command]luacheck --version"
          luacheck --version
          echo "##[endgroup]"
        shell: bash
      - name: Run Luacheck Linter
        run: |
          luacheck . | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" | tee ${{ github.workspace }}/luacheck_output.txt
        shell: bash
        continue-on-error: true
        working-directory: ${{ github.workspace }}
      - name: Post comment on PR
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          filePath: ${{ github.workspace }}/luacheck_output.txt
